### PR TITLE
fixes some stuff from #2

### PR DESCRIPTION
**Pull request by mipmip**
- preference panel
  - STRING configure "right click command for directories" (currently gnome-terminal....)
  - BOOL show/hide badge in indicator with number of dirty repo's
  - BOOL show changed files (I like to see changed repo-dirs only)

- config-file:
  - allow dir's glob e.g. ~/code* (I have prefixed all my git containing dirs with c e.g. cClient1 , cGnomeProjects)
  - new key repo_dirs for single repo_dirs in stead of parent dirs

- Also new project structure...

### CODE REVIEW

**Comment by eexpress** [comment]
Ha, You made so many commits, you should submit your own extension I think. I am not skill at PR, specially with conflict. :(
I will handle this slowly. If you publish your own extension I also glade to use it.

**Comment by eexpress** [comment]
After I do this.
```
git checkout -b mipmip-main main
git config pull.rebase true
git pull https://github.com/mipmip/gs-git.git main
```
I meet this error when `./install local-install`.
```
data>:13:1: Parse error: unexpected character `<', expected character `]'
```
which comes from this line.
```
gnome-extensions pack src \
    --force \
    --extra-source="../LICENSE" \
    --extra-source="git-monitor.json" \
    --extra-source="ui.js" \
    --extra-source="org.gnome.gitg-symbolic.svg" \
    --extra-source="org.gnome.gitg-symbolic-alert.svg" \
    --extra-source="../CHANGELOG.md"
```
I don't know why.

**Comment by mipmip** [comment]
@eexpress It is the malformed `metadata.json`. If you tidy this file it will work.

**Comment by eexpress** [comment]
Sorry for long AFK.
I read your code. It seems "Alert dirty repos" has not effect in code, I'm not sure what feature you want. "Show changed files" is same here.

I also want redefine those actions when right/left click on dir/file menuitems. So I will use "git difftool -d" with dirs, use "git difftool" with files and all set to button 1. Then use system open action on button 3. So we don't need prefs.js anymore.

Due to "Separate" directory settings in config file. It is not so important. 

Thanks for your PR, but I like more simple one. I think you can make your own extension and commit to https://extensions.gnome.org/. Your code is more structured and rational than my.

**Comment by mipmip** [comment]
Thanks for your reply. This PR was to big in the first place. I will fork this project and I'm very thankful for the inspiration you gave me.

**Pull request closed without merging**
